
/* PERSONAL OS 2.1 — UNIFIED EXECUTION ENGINE */
const POS21_VERSION="2.1.0";
function pos21Id(prefix,date,extra=""){return prefix+":"+date+(extra?":"+extra:"")}
function pos21Date(d=selected){return iso(d)}
function pos21Now(){return new Date().toISOString()}
async function pos21WriteExecution(record){const r={id:record.id||("exec:"+Date.now()),domain:record.domain,type:record.type,date:record.date||pos21Date(),planned:record.planned??null,actual:record.actual??null,status:record.status||"complete",metrics:record.metrics||{},updatedAt:pos21Now()};await pos2Put(r);return r}
async function pos21ReadExecutions(date){const all=await pos2All();return all.filter(r=>r.date===date&&(["executionRecord","strengthSet","run","bodyMetric","mealCompletion","studySession","taskCompletion"].includes(r.type)))}
function pos21Completion(plan,records){if(!plan.length)return 0;const p=plan.filter(x=>x.status==="complete").length;return Math.min(100,Math.round(Math.max(p,records.length)/plan.length*100))}
async function pos21SaveStrengthSet(date,exercise,setNo,weight,reps,target={}){if(!weight||!reps)return null;return pos21WriteExecution({id:pos21Id("strength",date,exercise.replace(/\W+/g,"_")+":"+setNo),domain:"fitness",type:"strengthSet",date,planned:{weight:target.weight||null,reps:target.reps||null,set:setNo},actual:{weight:Number(weight),reps:Number(reps),set:setNo},metrics:{volume:Number(weight)*Number(reps)},status:"complete"})}
async function pos21SaveRun(date,targetDistance,targetDuration,distance,duration){return pos21WriteExecution({id:pos21Id("run",date),domain:"fitness",type:"run",date,planned:{distance:targetDistance||null,duration:targetDuration||null},actual:{distance:Number(distance)||0,duration:Number(duration)||0},metrics:{pace:Number(distance)>0?Number(duration)/Number(distance):0},status:"complete"})}
async function pos21SaveWeight(date,weight){return pos21WriteExecution({id:pos21Id("weight",date),domain:"fitness",type:"bodyMetric",date,actual:{weight:Number(weight)},metrics:{weight:Number(weight)},status:"complete"})}
async function pos21CompleteMeal(date,meal,plannedMeal){return pos21WriteExecution({id:pos21Id("meal",date,meal),domain:"nutrition",type:"mealCompletion",date,planned:{meal,planned:plannedMeal||null},actual:{meal,completed:true},status:"complete"})}
async function pos21CompleteStudy(date,minutes,targetMinutes=60){return pos21WriteExecution({id:pos21Id("study",date),domain:"education",type:"studySession",date,planned:{minutes:targetMinutes},actual:{minutes:Number(minutes)||0},metrics:{adherence:Math.min(100,Math.round((Number(minutes)||0)/targetMinutes*100))},status:"complete"})}
async function pos21CompleteTask(date,title,completed=true){return pos21WriteExecution({id:pos21Id("task",date,title.replace(/\W+/g,"_")),domain:"tasks",type:"taskCompletion",date,planned:{title},actual:{completed},status:completed?"complete":"planned"})}

function pos21WeekStart(d=selected){const x=new Date(d);x.setHours(12,0,0,0);const diff=(x.getDay()+6)%7;x.setDate(x.getDate()-diff);return x}
function pos21RenderCalendar(){const box=document.getElementById("pos21CalendarBody");if(!box)return;const m=pos21WeekStart();let out='<div class="pos21-calendar">';for(let i=0;i<7;i++){const d=new Date(m);d.setDate(m.getDate()+i);const a=posPlannedActivities(d),key=iso(d);out+=`<div class="pos21-day ${key===iso(selected)?"active":""}" onclick="pos21SelectDate('${key}')"><b>${d.toLocaleDateString(undefined,{weekday:"short"})} ${d.getDate()}</b><span>${a.length} planned</span></div>`}box.innerHTML=out+"</div>"+Array.from({length:7},(_,i)=>{const d=new Date(m);d.setDate(m.getDate()+i);const a=posPlannedActivities(d);return `<div class="pos21-card"><div class="pos21-strong">${posDateLabel(d)}</div>${a.length?a.map(x=>`<div class="pos21-row"><div>${posEscape(x.time)}</div><div><div class="pos21-strong">${posEscape(x.title)}</div><div class="pos21-small">${posEscape(x.domain)}</div></div>${x.status==="complete"?'<span class="pos21-chip good">DONE</span>':'<span class="pos21-chip">PLANNED</span>'}</div>`).join(""):"<div class='pos21-empty'>No planned activities.</div>"}</div>`}).join("")}
function pos21SelectDate(key){selected=new Date(key+"T12:00:00");pos21CloseDrawer();pos21RefreshUI()}
async function pos21RenderData(){const box=document.getElementById("pos21DataBody");if(!box)return;const all=await pos2All(),domains=pos2DomainSummary(all),storage=JSON.stringify(all).length;box.innerHTML=`<div class="pos21-card"><div class="pos21-strong">Local database operational</div><div class="pos21-small">${all.length} records • ${(storage/1024).toFixed(1)} KB</div></div><div class="pos21-card">${Object.entries(domains).map(([k,v])=>`<div class="pos21-row"><div>${k}</div><div>${v} records</div><span class="pos21-chip">DATA</span></div>`).join("")}</div><div class="pos21-card"><div class="pos21-actions"><button onclick="pos2ExportFullDatabase()">Export Database</button><button onclick="pos21ExportExecutionCSV()">Export Execution CSV</button><button onclick="pos21RestorePrompt()">Restore JSON</button></div></div><div class="pos21-card"><div class="pos21-row"><div>IndexedDB</div><div>Canonical data</div><span class="pos21-chip good">OK</span></div><div class="pos21-row"><div>PWA</div><div>Offline shell</div><span class="pos21-chip good">OK</span></div><div class="pos21-row"><div>Cloud Sync</div><div>Not configured</div><span class="pos21-chip warn">PENDING</span></div></div>`}
async function pos21ExportExecutionCSV(){const all=await pos2All(),rows=all.filter(x=>["executionRecord","strengthSet","run","bodyMetric","mealCompletion","studySession","taskCompletion"].includes(x.type));const h=["date","domain","type","planned","actual","metrics","status","updatedAt"],esc=v=>`"${String(typeof v==="object"?JSON.stringify(v):v??"").replace(/"/g,'""')}"`,csv=[h.join(","),...rows.map(r=>h.map(k=>esc(r[k])).join(","))].join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="Personal_OS_2.1_Execution.csv";a.click()}
function pos21RestorePrompt(){const i=document.createElement("input");i.type="file";i.accept=".json,application/json";i.onchange=async()=>{try{const p=JSON.parse(await i.files[0].text());for(const r of p.records||[])await pos2Put(r);alert("Restore complete.");pos21RenderData()}catch(e){alert("Restore failed: invalid JSON backup.")}};i.click()}
function pos21OpenData(){document.getElementById("pos21DataModal").classList.add("open");pos21RenderData()}function pos21CloseData(){document.getElementById("pos21DataModal").classList.remove("open")}
function pos21OpenCalendar(){document.getElementById("pos21Drawer").classList.add("open");pos21RenderCalendar()}function pos21CloseDrawer(){document.getElementById("pos21Drawer").classList.remove("open")}
function pos21OpenExecution(title,sub,body){document.getElementById("pos21ModalTitle").textContent=title;document.getElementById("pos21ModalSub").textContent=sub;document.getElementById("pos21ModalBody").innerHTML=body;document.getElementById("pos21ExecutionModal").classList.add("open")}function pos21CloseModal(){document.getElementById("pos21ExecutionModal").classList.remove("open")}

function pos21OpenStrength(){const ex=["Squat","Bench Press","Row","Romanian Deadlift"];pos21OpenExecution("Today's Strength","Set-by-set execution",ex.map((x,i)=>`<div class="pos21-card"><div class="pos21-toolbar"><div><div class="pos21-strong">${x}</div><div class="pos21-small">Set ${i+1}</div></div><span class="pos21-chip">INPUT</span></div><div class="pos21-set"><div>#${i+1}</div><div><label>WEIGHT</label><input class="pos21-input" id="p21sw${i}" type="number" step=".5"></div><div><label>REPS</label><input class="pos21-input" id="p21sr${i}" type="number"></div><button type="button" onclick="this.parentElement.querySelector('input').focus()">✓</button></div></div>`).join("")+`<div class="pos21-actions" style="margin-top:10px"><button onclick="pos21SaveWorkout()">Save Workout</button></div>`)}
async function pos21SaveWorkout(){const ex=["Squat","Bench Press","Row","Romanian Deadlift"];for(let i=0;i<ex.length;i++){const w=Number(document.getElementById("p21sw"+i)?.value),r=Number(document.getElementById("p21sr"+i)?.value);if(w&&r)await pos21SaveStrengthSet(pos21Date(),ex[i],i+1,w,r,{})}await pos21WriteExecution({id:pos21Id("workout",pos21Date()),domain:"fitness",type:"executionRecord",date:pos21Date(),planned:{programWeek:posWeek(selected)},actual:{completed:true},status:"complete"});pos21CloseModal();pos21RefreshUI()}
function pos21OpenRun(){pos21OpenExecution("Today's Run","Capture actual distance and duration",`<div class="pos21-card"><label class="pos21-small">DISTANCE (MI)</label><input class="pos21-input" id="p21runDist" type="number" step=".01"><div style="margin-top:8px"><label class="pos21-small">DURATION (MIN)</label><input class="pos21-input" id="p21runTime" type="number" step=".1"></div><div class="pos21-actions" style="margin-top:10px"><button onclick="pos21SaveRunUI()">Save Run</button></div></div>`)}
async function pos21SaveRunUI(){const d=Number(document.getElementById("p21runDist").value),t=Number(document.getElementById("p21runTime").value);if(!d||!t)return;await pos21SaveRun(pos21Date(),null,null,d,t);pos21CloseModal();pos21RefreshUI()}
function pos21OpenWeight(){pos21OpenExecution("Body Weight","Capture today's weight",`<div class="pos21-card"><label class="pos21-small">WEIGHT (LB)</label><input class="pos21-input" id="p21weight" type="number" step=".1"><div class="pos21-actions" style="margin-top:10px"><button onclick="pos21SaveWeightUI()">Save Weight</button></div></div>`)}
async function pos21SaveWeightUI(){const w=Number(document.getElementById("p21weight").value);if(!w)return;await pos21SaveWeight(pos21Date(),w);pos21CloseModal();pos21RefreshUI()}
function pos21OpenMeal(){pos21OpenExecution("Meal Completion","Capture today's nutrition execution",["Breakfast","Lunch","Dinner"].map(m=>`<div class="pos21-card"><div class="pos21-row"><div>${m}</div><div>Mark complete</div><button onclick="pos21SaveMealUI('${m.toLowerCase()}')">Complete</button></div></div>`).join(""))}
async function pos21SaveMealUI(meal){await pos21CompleteMeal(pos21Date(),meal);pos21CloseModal();pos21RefreshUI()}
function pos21OpenStudy(){pos21OpenExecution("Network+ Study","Capture today's education execution",`<div class="pos21-card"><label class="pos21-small">MINUTES STUDIED</label><input class="pos21-input" id="p21study" type="number" value="60"><div class="pos21-actions" style="margin-top:10px"><button onclick="pos21SaveStudyUI()">Save Study</button></div></div>`)}
async function pos21SaveStudyUI(){const m=Number(document.getElementById("p21study").value)||0;await pos21CompleteStudy(pos21Date(),m);pos21CloseModal();pos21RefreshUI()}
function pos21OpenTask(title){pos21OpenExecution("Task Completion","Capture actual result",`<div class="pos21-card"><div class="pos21-strong">${posEscape(title)}</div><div class="pos21-actions" style="margin-top:10px"><button onclick='pos21SaveTaskUI(${JSON.stringify(title)})'>Complete Task</button></div></div>`)}
async function pos21SaveTaskUI(title){await pos21CompleteTask(pos21Date(),title,true);pos21CloseModal();pos21RefreshUI()}

async function pos21Progress(){const box=document.getElementById("pos21ProgressHost");if(!box)return;const plan=posPlannedActivities(selected),records=await pos21ReadExecutions(pos21Date()),overall=pos21Completion(plan,records),domains=["Fitness","Nutrition","Education","Household"];box.innerHTML=`<div class="pos21-card"><div class="pos21-strong">Today's execution</div><div class="pos21-small">${records.length} actual records</div><div class="pos21-progress"><div style="width:${overall}%"></div></div><div class="pos21-small" style="margin-top:5px">${overall}% complete</div></div>`+domains.map(d=>{const p=plan.filter(x=>x.domain===d),r=records.filter(x=>(d==="Household"?"tasks":d.toLowerCase())===x.domain),v=pos21Completion(p,r);return `<div class="pos21-card"><div class="pos21-row"><div>${d}</div><div>${r.length}/${p.length}</div><span class="pos21-chip">${v}%</span></div><div class="pos21-progress"><div style="width:${v}%"></div></div></div>`}).join("")}

function pos21Quick(type){if(type==="strength")pos21OpenStrength();else if(type==="run")pos21OpenRun();else if(type==="weight")pos21OpenWeight();else if(type==="meal")pos21OpenMeal();else if(type==="study")pos21OpenStudy()}
function pos21RefreshUI(){try{refineRefresh()}catch(e){}try{posDomainRefreshAll()}catch(e){}try{pos21Progress()}catch(e){}}
document.addEventListener("keydown",e=>{if(e.key==="Escape"){pos21CloseModal();pos21CloseDrawer();pos21CloseData()}});
